data/faq.js

added a benefits FAQ

---

data/faq/fellow_requirements.md

Replaced Coala references and links

Update fellow requirements

---

data/about.md

added note about relocation expense support

Add note about relocation assistance

---

_projects/ashlar.md

A discussion was started about developing a summer project to further explore feasibility of further Ashlar development. This PR initially stubs out a project page for Ashlar. The proposal can be improved via futher commits/PRs here.

Add Ashlar to 2018 projects

---

_data/mentors.yml
_projects/roman_tobler.md

This PR adds the `Foot Steps of Rome: Calculating the Cost of Travel in the Roman Empire` project proposal.

Roman Cost Distance Proposal

---

page-faq.md

Added FAQ about program promotion

---

_config.yml
_layouts/default.html
_projects/_template.md
_projects/ashlar.md
_projects/cloud_detection.md
_projects/lambda_tiles.md
_projects/roman_tobler.md
_projects/topojson_vector_data.md
page-about.md
page-faq.md
page-home.html
page-projects.html

* edited SEO text on Project page template
* added SEO descriptions and text edits on Project pages
* removed SEO TODO comment from layouts default
* added titles and SEO descriptions to high order pages
* Closes #20

Add titles and SEO descriptions

---

_projects/bus_routing.md

@lossyrob  there are a number of things in here that I wasn't sure about but took a stab at. feel free to make any changes or let me know if you have any questions. 
My main big picture comment is that the way I wrote it is a little unspecific, there are a lot of potential tasks in there. I am thinking that this would give us a lot of options that we can narrow down from, but let me know if you want me to get more specific.

bus routing description

---

_data/mentors.yml
_includes/call-to-action.html
_includes/footer.html
_includes/hero-post.html
_includes/navbar.html
page-faq.md
page-home.html

- fixes #14
- Adds the google hire link to all apply links/buttons
fixes #37 
- removes the duplicated Jacob Bouffard mentor
fixes one broken faq link from #16 
- Changes the first duplicate `#faq-4` anchor link and tag to `#faq-3`

adds google hire link, remove duplicate mentor, fix faq anchor

---

_projects/ashlar.md
_projects/bus_routing.md
_projects/lambda_tiles.md
_projects/opentripplanner.md
_projects/raster_vision.md
_projects/roman_tobler.md
_projects/topojson_vector_data.md

Established consistency across project markdowns

---

page-about.md
page-faq.md

While reading over the site before emailing it to the CS chair at the old Alma Mater, a few small copy issues caught my attention.
- "for 3-months" -> "for 3 months"
- "acceptanced" -> "accepted"
- "project requires to do so" -> "project requires one"
- punctuation consistency in lists (i.e. periods for all items or for none, not a mix)

Make minor edits for issues I noticed while reading the site

---

_config.yml
_includes/call-to-action.html

Close Summer 2018 applications.

---

_includes/footer.html

Updates the text and adds a link to our Machine Learning services page.
- `git pull`
- Go to homepage
- Look at footer and compare to azavea.com's

Update footer to match azavea.com

---

page-about.md
page-faq.md

- Change B Corp link URL
- Add reference to Earth on AWS program
- Edit FAQ copy
Closes #44, closes #46, closes #47

Edit copy on About and FAQ pages

---

_projects/bus_routing.md

My proposal for the School Bus 2019 summer fellowship project.
Largely identical to last year's version in terms of text, however I have made changes to put a greater emphasis on upgrading the framework and working on the computer science rather than software engineering side of the project.  I have upgraded the difficulty from "easy" to "very challenging"; I am hoping to attract applicants who want a challenge.

2019 School Bus

---

_projects/raster_vision.md

This adds the Raster Vision OSF project for Summer of 2019.
A major difference between this year's and last year's is, while the previous year focused on building out functionality in Raster Vision, this year's project focuses on utilizing Raster Vision to apply deep learning to a novel problem.

Raster vision 2019

---

_projects/area_indicators.md

This is a project proposal to create a Scala replacement to the Climate Change API, building on top of the work of @jamesmcclain in creating the proof-of-concept [`climate-backend`](https://github.com/azavea/climate-backend)
This is heavily cribbed off of an R+D proposal by @CloudNiner (https://github.com/azavea/azavea-10-percent-time/pull/252/files).

Area indicators proposal

---

_projects/geotrellis-vt-server.md

This is a project proposal to create a dynamic vector tile server using scala + GeoTrellis.

GeoTrellis Vector Tile Server

---

README.md
_config.yml
_data/mentors.yml
_includes/call-to-action.html
_includes/footer.html
_includes/hero-post.html
_includes/navbar.html
_projects/2018/ashlar.md
_projects/2018/lambda_tiles.md
_projects/2018/opentripplanner.md
_projects/2018/roman_tobler.md
_projects/2018/topojson_vector_data.md
_projects/area_indicators.md
_projects/beb_vectortile_refactor.md
_projects/bus_routing.md
_projects/geotrellis-vt-server.md
_projects/raster_vision.md
page-home.html

This PR, once merged, will open up applications for 2019.
TODO:

Open up registration for Summer 2019

---

_config.yml
_includes/_home/home.html
_includes/call-to-action.html
_includes/footer.html
_includes/navbar.html
page-faq.md

This PR adds the information about the Summer 2020 fellowship - that we are putting the program on hiatus for this year, and will pick it back up next year.

2020 update
